version: "3"
services:
  app:
    container_name: MaijnelliWebApp
    build: .
    command: nodemon --watch /usr/src/app -e js app.js
    ports:
      - "3000:3000"
    links:
      - "mongo:mongosrv"
  mongo:
    container_name: MaijnelliMongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'